# Generated by Django 3.2.24 on 2024-02-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='owener',
            new_name='owner',
        ),
    ]
